### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by sohilpandya** [FAC10/week1-jzlp#50]
Hey @/all

Turns out the site doesn't look great on mobile. Have a look at the image below. 
![img_0150](https://cloud.githubusercontent.com/assets/2305591/23299238/b36d1186-fa78-11e6-9709-d367b9ce6f5a.PNG)

It'll be good to make the site readable as a first step on mobile.

**Comment by lucyrose93** [comment]
Thanks! We think we solved this by adding min dimensions to vh
